import Head from 'next/head'
import Image from 'next/image'
import Biljke from '../components/Biljke/Biljke'
import CreateBiljkeModal from '../components/Biljke/CreateBiljkeModal'
import styles from '../styles/Biljke.module.css'
//import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div id="pageId" className={styles.biljkePage}>
       <Head>
        <title>iPlants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/3e3f615792.js" crossOrigin="anonymous"></script>
      </Head>

      <Biljke />
      <CreateBiljkeModal />
      
    </div>
  )
}

