//BILJKE
export const BILJKE_GET_LOADING = 'BILJKE_GET_LOADING';
export const BILJKE_GET = 'BILJKE_GET';
export const BILJKE_GET_FAIL = 'BILJKE_GET_FAIL';

export const BILJKE_CREATE_LOADING = 'BILJKE_CREATE_LOADING';
export const BILJKE_CREATE = "BILJKE_CREATE";
export const BILJKE_CREATE_FAIL = 'BILJKE_CREATE_FAIL';

export const BILJKE_DELETE_LOADING = 'BILJKE_DELETE_LOADING';
export const BILJKE_DELETE = "BILJKE_DELETE";
export const BILJKE_DELETE_FAIL = 'BILJKE_DELETE_FAIL';

export const BILJKE_UPDATE_LOADING = 'BILJKE_UPDATE_LOADING';
export const BILJKE_UPDATE = "BILJKE_UPDATE";
export const BILJKE_UPDATE_FAIL = 'BILJKE_UPDATE_FAIL';

//export const BILJKE_RESET_MODAL_FORM = 'BILJKE_RESET_MODAL_FORM';
export const BILJKA_DETAILS_GET_LOADING = 'BILJKA_DETAILS_GET_LOADIN';
export const BILJKA_DETAILS_GET = 'BILJKA_DETAILS_GET';
export const BILJKA_DETAILS_GET_FAIL = 'BILJKA_DETAILS_GET_FAIL';

//NARUDZBE
export const NARUDZBE_GET_LOADING = 'NARUDZBE_GET_LOADING';
export const NARUDZBE_GET = 'NARUDZBE_GET';
export const NARUDZBE_GET_FAIL = 'NARUDZBE_GET_FAIL';

export const NARUDZBE_CREATE_LOADING = 'NARUDZBE_CREATE_LOADING';
export const NARUDZBE_CREATE = "NARUDZBE_CREATE";
export const NARUDZBE_CREATE_FAIL = 'NARUDZBE_CREATE_FAIL';

export const NARUDZBE_DELETE_LOADING = 'NARUDZBE_DELETE_LOADING';
export const NARUDZBE_DELETE = "NARUDZBE_DELETE";
export const NARUDZBE_DELETE_FAIL = 'NARUDZBE_DELETE_FAIL';

export const NARUDZBE_UPDATE_LOADING = 'NARUDZBE_UPDATE_LOADING';
export const NARUDZBE_UPDATE = "NARUDZBE_UPDATE";
export const NARUDZBE_UPDATE_FAIL = 'NARUDZBE_UPDATE_FAIL';

export const SEARCH_BILJKA_STANJE_LOADING = 'SEARCH_BILJKA_STANJE_LOADING'
export const SEARCH_BILJKA_STANJE_SUCCESS = 'SEARCH_BILJKA_STANJE_SUCCESS'
export const SEARCH_BILJKA_STANJE_FAIL = 'SEARCH_BILJKA_STANJE_FAIL'

export const NARUDZBE_RESET_MODAL_FORM = 'NARUDZBE_RESET_MODAL_FORM'

export const NARUDZBE_STATUS_UPDATE = 'NARUDZBE_STATUS_UPDATE'

export const GET_LISTA_PROIZVODA_LOADING = 'GET_LISTA_PROIZVODA_LOADING'
export const GET_LISTA_PROIZVODA = 'GET_LISTA_PROIZVODA'

// SKLADISTE

export const SKLADISTE_BILJKE_GET_LOADING = 'SKLADISTE_BILJKE_GET_LOADING';
export const SKLADISTE_BILJKE_GET = 'SKLADISTE_BILJKE_GET';
export const SKLADISTE_BILJKE_GET_FAIL = 'SKLADISTE_BILJKE_GET_FAIL';

export const LOKACIJE_GET_LOADING = 'LOKACIJE_GET_LOADING';
export const LOKACIJE_GET = 'LOKACIJE_GET';
export const LOKACIJE_GET_FAIL = 'LOKACIJE_GET_FAIL';

export const GET_IMANJA_LOKACIJA_LOADING = 'GET_IMANJA_LOKACIJA_LOADING';
export const GET_IMANJA_LOKACIJA = 'GET_IMANJA_LOKACIJA';
export const GET_IMANJA_LOKACIJA_FAIL = 'GET_IMANJA_LOKACIJA_FAIL';

export const GET_MIKROLOKACIJE_IMANJE_LOADING = 'GET_MIKROLOKACIJE_IMANJE_LOADING';
export const GET_MIKROLOKACIJE_IMANJE = 'GET_MIKROLOKACIJE_IMANJE';
export const GET_MIKROLOKACIJE_IMANJE_FAIL = 'GET_MIKROLOKACIJE_IMANJE_FAIL';

export const BILJKA_SKLADISTE_CREATE_LOADING = 'BILJKA_SKLADISTE_CREATE_LOADING';
export const BILJKA_SKLADISTE_CREATE = "BILJKA_SKLADISTE_CREATE";
export const BILJKA_SKLADISTE_CREATE_FAIL = 'BILJKA_SKLADISTE_CREATE_FAIL';

export const GET_BILJKE_MIKROLOKACIJE_LOAD = 'GET_BILJKE_MIKROLOKACIJE_LOAD';
export const GET_BILJKE_MIKROLOKACIJE = "GET_BILJKE_MIKROLOKACIJE";
export const GET_BILJKE_MIKROLOKACIJE_FAIL = 'GET_BILJKE_MIKROLOKACIJE_FAIL';

export const GET_MIKROLOKACIJE_LOAD = 'GET_MIKROLOKACIJE_LOAD';
export const GET_MIKROLOKACIJE = "GET_MIKROLOKACIJE";
export const GET_MIKROLOKACIJE_FAIL = 'GET_MIKROLOKACIJE_FAIL';

export const BILJKE_STANJE_DELETE_LOADING = 'BILJKE_STANJE_DELETE_LOADING';
export const BILJKE_STANJE_DELETE = "BILJKE_STANJE_DELETE";
export const BILJKE_STANJE_DELETE_FAIL = 'BILJKE_STANJE_DELETE_FAIL';

export const IS_STANJE_EXIST_SUCCESS = 'IS_STANJE_EXIST_SUCCESS';

export const SKLADISTE_RESET_MODAL_FORM = 'SKLADISTE_RESET_MODAL_FORM'

export const SKLADISTE_DETAILS_BILJKE_GET_LOADING = 'SKLADISTE_DETAILS_BILJKE_GET_LOADING';
export const SKLADISTE_DETAILS_BILJKE_GET = 'SKLADISTE_DETAILS_BILJKE_GET';
export const SKLADISTE_DETAILS_BILJKE_GET_FAIL = 'SKLADISTE_DETAILS_BILJKE_GET_FAIL';

export const BILJKA_SKLADISTE_UPDATE_LOADING = 'BILJKA_SKLADISTE_UPDATE_LOADING';
export const BILJKA_SKLADISTE_UPDATE = 'BILJKA_SKLADISTE_UPDATE';
export const BILJKA_SKLADISTE_UPDATE_FAIL = 'BILJKA_SKLADISTE_UPDATE_FAIL';

export const FILTER_LOKACIJE = 'FILTER_LOKACIJE'

export const FILTER_BILJKE = 'FILTER_BILJKE'

